
(define %my-emacs-pkgs
  (list
   ;; emacsg
   "emacs-pgtk"
   "emacs-0x0"
   "emacs-arei"				;; use with guile-ares-rs
   "emacs-eat"
   "emacs-denote"
   "emacs-consult-denote"
   ;; "emacs-substitute"
   ;; "emacs-js2-mode"
   ;; "emacs-hydra"
   "emacs-helpful"
   "emacs-graphviz-dot-mode"
   ;; "emacs-graphql"
   "emacs-glsl-mode"
   ;; "emacs-gif-screencast" ;; can´t find any compatible screenshot app
   "emacs-geiser-guile"
   "emacs-geiser"
   "emacs-guix"
   "emacs-magit"
   "emacs-buffer-env"
   "emacs-burly"
   "emacs-flycheck"
   "emacs-flycheck-rust"
   "emacs-fontaine"
   "emacs-expand-region"
   "emacs-emojify"
   "emacs-elfeed"
   "emacs-elfeed-protocol"
   "emacs-envrc"
   "emacs-eat"
   "emacs-ef-themes"
   "emacs-miasma-theme"
   "emacs-hasliberg-theme"
   "emacs-eglot-jl"
   "emacs-denote"
   "emacs-doom-themes"
   "emacs-modus-themes"
   "emacs-miasma-theme"
   "emacs-hasliberg-theme"
   "emacs-org-modern"
   "emacs-nerd-icons"
   "emacs-doom-modeline"
   "emacs-dashboard"
   "emacs-corfu"
   "emacs-consult"
   "emacs-consult-denote"
   "emacs-consult-dir"
   ;; "emacs-bongo"
   "emacs-all-the-icons-dired"
   "emacs-all-the-icons-completion"
   "emacs-all-the-icons"
   "emacs-websocket"
   "emacs-simple-httpd@1.4.0"
   "emacs-visual-fill-column"
   "emacs-orderless"
   "emacs-org-modern"
   "emacs-vertico"
   "emacs-marginalia"
   "emacs-embark"
   "emacs-popper"
   "emacs-org"
   "emacs-org-superstar"
   ;; "emacs-org-ql"
   "emacs-citeproc"
   "emacs-citar"
   "emacs-citar-denote"
   "emacs-org-fancy-priorities"
   "emacs-qrencode"
   "emacs-saveplace-pdf-view"
   "emacs-pdf-tools"
   "emacs-org-noter"
   ;; "emacs-org-appear"
   "emacs-org-tree-slide"
   "emacs-org-download"
   "emacs-org-drill"
   "emacs-toc-org"
   "emacs-org-modern"
   "emacs-org-pomodoro"
   ;; "emacs-ox-reveal"
   ;; "emacs-plantuml-mode"
   "emacs-peg"
   "emacs-org-present"
   ;; "emacs-minimap"
   "emacs-tablist"
   ;; "emacs-sml-mode"
   "emacs-beacon"
   "emacs-keycast"
   "emacs-rainbow-delimiters"
   "emacs-highlight-indent-guides"
   "emacs-org-fragtog"
   "emacs-yaml-mode"
   "emacs-nov-el"
   "emacs-notmuch"
   "emacs-consult-notmuch"
   "emacs-multiple-cursors"
   "emacs-smartparens"
   "emacs-aggressive-indent"
   "emacs-ccls"
   "emacs-dap-mode"
   "emacs-pyvenv"
   ;; "emacs-jupyter"
   ;; "emacs-ement"
   ;; "emacs-julia-mode"
   ;; "emacs-julia-repl"
   ;; "emacs-typescript-mode"
   "emacs-json-mode"
   "emacs-jsonrpc"
   ;; "emacs-js2-mode"
   ;; "emacs-lua-mode"
   "emacs-cmake-mode"
   "emacs-powershell"
   ;; "emacs-kotlin-mode"
   "emacs-cape"
   "emacs-tempel"
   "emacs-tempel-collection"
   "emacs-transient"
   "emacs-eros"
   "emacs-shackle"
   "emacs-kind-icon"
   "emacs-org-contrib"
   "emacs-mpv"
   "emacs-font-lock+"
   "emacs-ox-haunt"
   "emacs-langtool"
   "emacs-nasm-mode"
   "emacs-odin-mode"
   "emacs-odin-ts-mode"
   "emacs-flycheck-odin"
   "emacs-svg-lib@0.2.8"
   "emacs-ace-window-next"
   "emacs-htmlize"))
