#!/usr/bin/env -S bash
# Remove the new tag from messages that are still tagged as new
notmuch tag -new tag:new

# Sync mail messages
#mbsync --verbose all
mbsync all

#notmuch search --output=files --format=text0 tag:killed | xargs -r0 rm
